# Generated by Django 6.0 on 2026-07-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('category', models.CharField(choices=[('web', 'Développement web'), ('video', 'Vidéo IA publicitaire')], max_length=10, verbose_name='Catégorie')),
                ('sector', models.CharField(blank=True, help_text='Pour les vidéos IA : e-commerce, restauration, immobilier…', max_length=100, verbose_name='Secteur')),
                ('description', models.TextField(verbose_name='Description')),
                ('problem', models.TextField(blank=True, verbose_name='Problème client résolu')),
                ('solution', models.TextField(blank=True, verbose_name='Solution apportée')),
                ('result', models.TextField(blank=True, verbose_name='Résultat mesurable')),
                ('stack', models.JSONField(default=list, help_text='Liste JSON, ex. ["Django", "PostgreSQL"]', verbose_name='Stack / Outils')),
                ('live_url', models.URLField(blank=True, verbose_name='URL du site')),
                ('video_url', models.URLField(blank=True, help_text='Lien YouTube ou Vimeo pour les vidéos IA', verbose_name='URL de la vidéo')),
                ('thumbnail', models.ImageField(upload_to='projects/', verbose_name='Miniature')),
                ('featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
