# Generated by Django 5.2.17 on 2026-09-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_seed_video_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_file',
            field=models.FileField(blank=True, help_text='Vidéo à uploader directement (MP4, compressée). Lue dans une pop-up au clic.', upload_to='projects/videos/', verbose_name='Fichier vidéo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien YouTube ou Vimeo — conservé pour les anciens projets, préférer le fichier vidéo ci-dessous.', verbose_name='URL de la vidéo (ancien format)'),
        ),
    ]
