# Generated by Django 6.0.7 on 2026-08-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Azeez Ridwan', max_length=100, verbose_name='Nom affiché')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('whatsapp', models.CharField(blank=True, help_text='Format international sans le "+", ex. 2250700000000', max_length=20, verbose_name='Numéro WhatsApp')),
                ('telegram', models.CharField(blank=True, help_text='Sans le @, ex. azeezridwan', max_length=50, verbose_name='Identifiant Telegram')),
                ('linkedin', models.URLField(blank=True, verbose_name='URL LinkedIn')),
                ('github', models.URLField(blank=True, verbose_name='URL GitHub')),
                ('location', models.CharField(default='Abidjan, Côte d’Ivoire', max_length=150, verbose_name='Localisation')),
                ('available', models.BooleanField(default=True, help_text='Contrôle le statut affiché sur le site (pastille verte du hero et de la section À propos).', verbose_name='Disponible pour de nouveaux projets')),
            ],
            options={
                'verbose_name': 'Réglages du site',
                'verbose_name_plural': 'Réglages du site',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('category', models.CharField(choices=[('dev', 'Développement Web'), ('video', 'IA Créative & Vidéo')], max_length=10, verbose_name='Catégorie')),
                ('detail', models.CharField(help_text='Ex. "Expert" pour une compétence dev, "Génération vidéo IA" pour un outil.', max_length=100, verbose_name='Niveau / Usage')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Compétence / Outil',
                'verbose_name_plural': 'Compétences & Outils',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
