# Generated by Django 5.2.17 on 2026-09-03 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_site_settings_and_skills'),
        ('projects', '0004_project_video_file_alter_project_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_video_1',
            field=models.ForeignKey(blank=True, help_text="Vidéo mise en avant dans la section « De l'Imagination à la Réalité Cinématique ».", limit_choices_to={'category': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project', verbose_name='Vidéo IA en avant #1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_video_2',
            field=models.ForeignKey(blank=True, help_text='Deuxième vidéo mise en avant dans la même section.', limit_choices_to={'category': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project', verbose_name='Vidéo IA en avant #2'),
        ),
    ]
