# Generated by Django 3.2.8 on 2021-10-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologie',
            options={'verbose_name': 'Technologie', 'verbose_name_plural': 'Technologies'},
        ),
    ]
