# Generated by Django 3.2.8 on 2021-12-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_technologie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='moi_en_avant',
            name='texte',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
