# Generated by Django 3.2.8 on 2021-12-25 10:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_moi_en_avant_texte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='date',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='work',
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
