# Generated by Django 3.2.8 on 2021-12-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20211225_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='description_contact',
            new_name='description_project',
        ),
    ]
