# Generated by Django 3.2.8 on 2021-12-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_description_contact_website_description_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='description_conctact',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
