# Generated by Django 3.2.8 on 2022-01-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_website_description_conctact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moi_en_avant',
            name='technologie',
        ),
        migrations.AddField(
            model_name='moi_en_avant',
            name='technologie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='techno', to='website.technologie'),
            preserve_default=False,
        ),
    ]
