# Generated by Django 3.2.8 on 2022-01-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20220101_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moi_en_avant',
            name='technologie',
        ),
        migrations.AddField(
            model_name='moi_en_avant',
            name='technologie',
            field=models.ManyToManyField(related_name='techno', to='website.Technologie'),
        ),
    ]
