# Generated by Django 3.2.8 on 2022-01-01 11:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20220101_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nom'),
        ),
    ]
