# Generated by Django 3.2.8 on 2022-01-01 12:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_projet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='description2',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projet',
            name='picture2',
            field=models.FileField(default=1, upload_to='image_projet'),
            preserve_default=False,
        ),
    ]
