# Generated by Django 6.0 on 2026-07-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Prénom & Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('need', models.CharField(choices=[('web', 'Application web / API'), ('video', 'Vidéo publicitaire IA'), ('combo', 'Pack Combo (Dev + Vidéo)'), ('other', 'Autre')], max_length=10, verbose_name='Type de besoin')),
                ('budget', models.CharField(choices=[('lt100', 'Moins de 100 000 FCFA'), ('100-300', '100 000 – 300 000 FCFA'), ('300-600', '300 000 – 600 000 FCFA'), ('gt600', '600 000 FCFA et plus')], max_length=10, verbose_name='Budget estimé')),
                ('message', models.TextField(verbose_name='Message / Description du projet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('handled', models.BooleanField(default=False, verbose_name='Traité')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
