# Generated by Django 6.0 on 2026-07-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='need',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
