# Generated by Django 5.0.14 on 2026-08-30 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contactmessage_budget_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prospect / Message', 'verbose_name_plural': 'Prospects / Messages'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Budget estimé (FCFA)'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='company',
            field=models.CharField(blank=True, max_length=150, verbose_name='Entreprise / Organisation'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier contact'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes internes / Suivi'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone / WhatsApp'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='service_type',
            field=models.CharField(choices=[('web', 'Développement Web'), ('video', 'Vidéo IA'), ('combo', 'Pack Dev + Vidéo'), ('consulting', 'Consulting & Audit'), ('other', 'Autre besoin')], default='web', max_length=20, verbose_name='Type de prestation'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacté'), ('proposal', 'Proposition envoyée'), ('won', 'Projet Gagné'), ('completed', 'Livré / Terminé'), ('lost', 'Archivé / Sans suite')], default='new', max_length=20, verbose_name='Statut CRM'),
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('note', 'Note interne'), ('call', 'Appel téléphonique'), ('whatsapp', 'Échange WhatsApp'), ('email', 'Email envoyé'), ('meeting', 'Rendez-vous / Visio'), ('status_change', 'Changement d’étape')], default='note', max_length=20, verbose_name='Type d’action')),
                ('content', models.TextField(verbose_name='Détails / Compte-rendu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='contact.contactmessage', verbose_name='Prospect')),
            ],
            options={
                'verbose_name': 'Activité prospect',
                'verbose_name_plural': 'Activités prospects',
                'ordering': ['-created_at'],
            },
        ),
    ]
