# Generated by Django 6.0 on 2026-07-08 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('author_title', models.CharField(max_length=150, verbose_name='Poste / Entreprise')),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('avatar', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Photo')),
                ('featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='Projet lié')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
